### ISSUE TITLE
Reference and PRIDE dataset in TMT vignette are incorrect

### ISSUE THREAD

**Issue by pwilmart** [bartongroup/Proteus#22]
I think the publication is from MCP in 2018: "Proteomic Analysis of the Cell Cycle of Procylic Form Trypanosoma brucei." with a PRIDE number of PXD008741. The listed publication and data are from a much larger label-free protein interaction study.

**Comment by MarekGierlinski** [comment]
Thank you for this information. I will correct the reference in the next release.

**Comment by MarekGierlinski** [comment]
Fixed in release 0.2.9.
