### ISSUE TITLE
Vignettes not installing?

### ISSUE THREAD

**Issue by ar3781** [bartongroup/Proteus#25]
I've downloaded the package but when I try to do the tutorial with vignette("proteus", package="proteus"), I get a message that the vignette isn't found. If I just type vignette(package="proteus") , it says no vignettes found. Not sure how to get around this.

**Comment by MarekGierlinski** [comment]
Did you use `build_vignettes = TRUE` when installing Proteus? If this doesn't work, I added links to online copies of vignettes. Please refer to `README.md` on the main GitHub page for Proteus.
