### ISSUE TITLE
Spike-in SILAC?

### ISSUE THREAD

**Issue by docdot** [bartongroup/Proteus#26]
Hi, 

It is not a proper issue. But, it was not clear for me in the vignette https://github.com/bartongroup/Proteus/blob/master/vignettes/SILAC.Rmd if the proteusSILAC also works for Spike-in SILAC (http://dx.doi.org/10.1038/nprot.2010.192). Is it possible using it to this end as well?

Many thanks,

Raphael

**Comment by MarekGierlinski** [comment]
I have never used it with SILAC spike-in, but I think there should be no problem. It is still a SILAC, so all processing steps should be the same. The only difference is interpretation at the end: instead of one biological condition versus another you have a condition versus a standard.
