### ISSUE TITLE
Problem with parallel::mclapply on Windows

### ISSUE THREAD

**Issue by Pam65** [bartongroup/Proteus#27]
Dear all,
I'm trying to run Proteus on Windows and I receive this error message:

> peptides <- makePeptideTable(evidence, metadata)
Error in parallel::mclapply(unique(sequences), function(s) { : 
  'mc.cores' > 1 is not supported on Windows

I'm just a poor biologist with very basic knowledge of programming ;-)
Can you suggest a solution to this problem?

Thank you in advance,
Paola

**Comment by MarekGierlinski** [comment]
Hi Paola,

Alas, multi-core computations are not supported in R under Windows. You can
run makePeptideTable with a parameter "ncores=1".

Marek

**Comment by Pam65** [comment]
Hi Marek,
That was fast!
I’ll try to change the parameter.
Thank you ☺
All the best,
Paola

**Comment by MarekGierlinski** [comment]
Proteus now checks the OS and if it is Windows, it sets ncores to 1.
