### ISSUE TITLE
Reduced number of entries from readProteinsGroups

### ISSUE THREAD

**Issue by gurpreet-bioinfo** [bartongroup/Proteus#31]
Hi there,

I am using **proteus** to directly analyse MaxQuant output file `proteinGroups.txt` acc. to [section 5.5](http://www.compbio.dundee.ac.uk/user/mgierlinski/proteus/proteus.html). 
My `proteinGroups.txt` has 4916 entries, but when I read it, the number of entries are reduced (4753). Following is the command (after creating customized meta file and measure.cols):
```
prot.MQ <- readProteinGroups("Q:/Proteomics/proteinGroups.txt", meta.MQ, measure.cols = measure.cols, data.cols = proteinColumns)     
```

`summary(prot.MQ)` shows all other information correctly, except the number of entries.

Would you please explain or if I miss something?

Thanks.
Gurpreet

**Comment by MarekGierlinski** [comment]
Hi Gurpreet,

When data are read into Proteus all entries with `Reverse` or `Potential contaminant` columns marked as "+" are removed. In addition the rows with no data (all measure columns are zero) are removed as well. This would be my guess why some entries are missing. They contain no useful data.

Marek

**Comment by gurpreet-bioinfo** [comment]
Thanks @MarekGierlinski for the explanation!
