### ISSUE TITLE
Error in the extraction commands while retrieving ids

### ISSUE THREAD

**Issue by gurpreet-bioinfo** [bartongroup/Proteus#32]
Hi there,

I followed [section 4.5](http://www.compbio.dundee.ac.uk/user/mgierlinski/proteus/proteus.html#protein-annotations) for protein annotations. By looking at the dataframe `ids`, it seems that it does not extract all the values for `uniprot` column from **prot.MQ.med$proteins**. This leads to **NA** under `uniprot, gene and protein names` for `res` dataframe,  for which uniprot annotation exists as evident from uniprot id under `protein` column.
I also verified this by manually searching in the UniProt for few proteins.

It all happens due to some error in the following extraction commands:
```
luni <- lapply(as.character(prot.MQ.med$proteins), function(prot) {
 if(grepl("sp\\|", prot)) {
   uniprot <- unlist(strsplit(prot, "|", fixed=TRUE))[2]
   c(prot, uniprot)
 }
})

ids <- as.data.frame(do.call(rbind, luni))
```

Would it be possible to correct this as it would be helpful to get the latest annotations?

Thanks.
Gurpreet

**Comment by MarekGierlinski** [comment]
This piece of code is only an example of how Uniprot identifiers can be extracted. It works only for a specific format of input data, with identifiers like `sp|P00546|CDK1_YEAST`. Clearly, your IDs are in a different format. This is really outside of the scope of Proteus and needs some basic R programming in order to convert IDs to a required format.

**Comment by gurpreet-bioinfo** [comment]
@MarekGierlinski Thanks for letting me know. I will do that.

**Comment by gurpreet-bioinfo** [comment]
Just for information, following is giving me correct ids:
```
luni <- lapply(as.character(prot.MQ.med$proteins), function(prot) {
 if(grepl("sp|tr\\|", prot)) {                                   # sp|tr
   uniprot <- unlist(strsplit(prot, "|", fixed=TRUE))[2]
   c(prot, uniprot)
 }
})

ids <- as.data.frame(do.call(rbind, luni))
```
