### ISSUE TITLE
PCA function missing

### ISSUE THREAD

**Issue by gurpreet-bioinfo** [bartongroup/Proteus#33]
Hi there,

I followed [section 5.5](http://www.compbio.dundee.ac.uk/user/mgierlinski/proteus/proteus.html) to analyze MaxQuant's proteinGroups.txt directly. Then I performed limma analysis and followed section 6.2 for visualization. Everything went very well. :-) Proteus is awesome.

However, I did not find any function to plot PCA directly like the others. Is there a possibility to do that with Proteus or is it an upcoming feature?

Thanks.
Gurpreet

**Comment by gurpreet-bioinfo** [comment]
Hi there,

Any updates here?

Thanks.
Gurpreet

**Comment by MarekGierlinski** [comment]
Function plotPCA() added.

**Comment by gurpreet-bioinfo** [comment]
> Function plotPCA() added.

Thanks @MarekGierlinski !
