### ISSUE TITLE
Setting different measure.cols for readProteinGroups

### ISSUE THREAD

**Issue by cmysrobinso** [bartongroup/Proteus#34]
Hi!
I wanted to use the LFQ intensities when reading from the ProteinGroups file directly, so I set measure.cols <- paste("LFQ intensity", meta$sample) as it talks about in the manual, but I keep getting the error that the columns are not unique. If I leave measure.cols to the default or NULL it works. I checked that the column/sample names are unique and they are, so I can't figure out what the issue is. Any help would be much appreciated. Thank you!

**Comment by MarekGierlinski** [comment]
`measure.cols` has to be a named vector. Try adding  `names(measure.cols) <- meta$sample` after paste.

**Comment by cmysrobinso** [comment]
Thank you very much!
