### ISSUE TITLE
Normalize the data of SILAC

### ISSUE THREAD

**Issue by yueli8** [bartongroup/Proteus#41]
Hello bartongroup,

Thank you for developing so nice software.

I have SILAC protein data from three patients. How can I normalize the `A10: Light/Heavy` value over these patients?

I studied the  `evidence.txt.gz` in the package `proteusLablFree`.  Which column is the ratio of `Light/Heavy`?

Thank you in advance for great help!

Best,

Yue

**Comment by MarekGierlinski** [comment]
SILAC data are processed differently. See the SILAC vignette:

http://www.compbio.dundee.ac.uk/user/mgierlinski/proteus/SILAC.html

Marek

**Comment by yueli8** [comment]
Hello MareGierlinski,

Thank you so much for your great help!

Best,

Yue
