### ISSUE TITLE
extract peptide/protein count

### ISSUE THREAD

**Issue by francescocay** [bartongroup/Proteus#44]
When using `plotCount(pepdat)`, does the function allow extraction of the calculated peptide/protein counts that are used for plotting (i.e. to be subsequently exported in a txt file)?

**Comment by MarekGierlinski** [comment]
No, it does not provide these numbers, but it is easy to find them. If `pdat` is a `proteusData` object, you can find protein counts using

```
cnt <- apply(pdat$tab, 2, function(x) sum(!is.na(x)))
```
