### ISSUE TITLE
Error in limmaRatioDE function

### ISSUE THREAD

**Issue by TaraBartolec** [bartongroup/Proteus#45]
Hello,

I've found an error in the code which describes the limmaRatioDE function, in R/func.R. It excludes DE of ratios from two biological replicate. I think it would just involve changing the length(sel) < 2. Would it be possible to change this?

```
sel <- which(meta$[condition] == condition
if(length(sel) < 3) stop("Need at least two replicates for one-sample differential expression.")
  tab <- tab[,sel]
```
Best,
Tara

**Comment by MarekGierlinski** [comment]
Fixed.
