### ISSUE TITLE
Not compatible with R version

### ISSUE THREAD

**Issue by cstgermain4** [bartongroup/Proteus#47]
I am trying to install proteusTMT and I get an error that it is not availble for my version of R (4.3.1). Is there an updated version?

**Comment by MarekGierlinski** [comment]
We are sorry, but Proteus is no longer developed, and we do not work on new updates. As this is open software, we encourage anyone to contribute to development of this package. Alternatively, we recommend reading *MaxQuant's* `proteinGroups` file directly in R and using available tools like *limma* to analyse proteomics data.
